// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: pkg/proto/upload.proto

package upload

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	UploadFileService_Upload_FullMethodName = "/proto.UploadFileService/Upload"
)

// UploadFileServiceClient is the client API for UploadFileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UploadFileServiceClient interface {
	Upload(ctx context.Context, opts ...grpc.CallOption) (UploadFileService_UploadClient, error)
}

type uploadFileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUploadFileServiceClient(cc grpc.ClientConnInterface) UploadFileServiceClient {
	return &uploadFileServiceClient{cc}
}

func (c *uploadFileServiceClient) Upload(ctx context.Context, opts ...grpc.CallOption) (UploadFileService_UploadClient, error) {
	stream, err := c.cc.NewStream(ctx, &UploadFileService_ServiceDesc.Streams[0], UploadFileService_Upload_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &uploadFileServiceUploadClient{stream}
	return x, nil
}

type UploadFileService_UploadClient interface {
	Send(*UploadRequest) error
	CloseAndRecv() (*UploadResponse, error)
	grpc.ClientStream
}

type uploadFileServiceUploadClient struct {
	grpc.ClientStream
}

func (x *uploadFileServiceUploadClient) Send(m *UploadRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *uploadFileServiceUploadClient) CloseAndRecv() (*UploadResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UploadFileServiceServer is the server API for UploadFileService service.
// All implementations should embed UnimplementedUploadFileServiceServer
// for forward compatibility
type UploadFileServiceServer interface {
	Upload(UploadFileService_UploadServer) error
}

// UnimplementedUploadFileServiceServer should be embedded to have forward compatible implementations.
type UnimplementedUploadFileServiceServer struct {
}

func (UnimplementedUploadFileServiceServer) Upload(UploadFileService_UploadServer) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}

// UnsafeUploadFileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UploadFileServiceServer will
// result in compilation errors.
type UnsafeUploadFileServiceServer interface {
	mustEmbedUnimplementedUploadFileServiceServer()
}

func RegisterUploadFileServiceServer(s grpc.ServiceRegistrar, srv UploadFileServiceServer) {
	s.RegisterService(&UploadFileService_ServiceDesc, srv)
}

func _UploadFileService_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UploadFileServiceServer).Upload(&uploadFileServiceUploadServer{stream})
}

type UploadFileService_UploadServer interface {
	SendAndClose(*UploadResponse) error
	Recv() (*UploadRequest, error)
	grpc.ServerStream
}

type uploadFileServiceUploadServer struct {
	grpc.ServerStream
}

func (x *uploadFileServiceUploadServer) SendAndClose(m *UploadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *uploadFileServiceUploadServer) Recv() (*UploadRequest, error) {
	m := new(UploadRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UploadFileService_ServiceDesc is the grpc.ServiceDesc for UploadFileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UploadFileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UploadFileService",
	HandlerType: (*UploadFileServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _UploadFileService_Upload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/proto/upload.proto",
}
